Features app
rachaouldbabaali/budget-app pull request #1
Opened 2023-09-12 22:51 UTC by rachaouldbabaali

Ruby on Rails capstone project - Budget app
In this project, I have implemented the following;

- [x] Use ruby gems as software packages system.

- [x] Install Ruby on Rails framework.
- [x] Understand Rails RESTful design and router.
- [x] Use controllers to handle requests and render empty views.
- [x] Use params from browser request in a safe way.
- [x] Use a preprocessed html file with embedded Ruby code.
- [x] Use layouts and templates for shared content.
- [x] Use database migration files to maintain database schema.
- [x] Use validations for models.
- [x] Secure app from n+1 problems.
- [x] Understand what ORM is.
- [x] Write SQL queries with ActiveRecord.
- [x] Set up associations between models.
- [x] Build a webapp that requires the user to log in.
- [x] Use devise gem for authentication.
- [x] Limit access to webapp resources based on authorization rules.
- [x] Analyze in writing why you have made a coding choice using one structure over another

2023-09-13 18:33 UTC, Davidosky007 requested changes
Hi @rachaouldbabaali 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## Highlights

* N+1 issue solved 👍 
* Well-written PR 👍 
* No linter errors 👍 
* Video presentation looks good 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-13 18:33 UTC, Davidosky007 commented on spec/features/expenses_spec.rb
> +    @group = Group.create(name: 'Food', icon: 'icons/food.PNG', user_id: @user.id)
* I get errors when I try to run your tests seems the errors come from the icons in your test as they are different from what you have in your assets folder Kindly put in the correct image title and extension and it should work for example( 'icons/food.jpg') 
![image](https://github.com/rachaouldbabaali/budget-app/assets/52497246/74cba160-a0b6-4d3e-9644-4e9ce33140bb)

2023-09-13 18:33 UTC, Davidosky007 commented on README.md
> +- Live Demo Link: will be updated when available
* Kindly add a working live demo link as it's a [requirement ](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=The%20project%20should%20be%20deployed%20and%20accessible%20online.)

2023-09-13 18:33 UTC, Davidosky007 commented on app/assets/stylesheets/style.css
> +.total_amount {
* As required : 
* You should follow these [design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), including:
Colors.
Typography: font face, size and weight.
Layout: composition and space between elements.
* Kindly use the given fonts and colors
![image](https://github.com/rachaouldbabaali/budget-app/assets/52497246/e4951fbd-f4db-4599-ba3e-256eb4eecd20)
![image](https://github.com/rachaouldbabaali/budget-app/assets/52497246/3df6b57d-4669-4828-b081-48b6cf58e454)

2023-09-14 09:57 UTC, DammyShittu requested changes
Hi @rachaouldbabaali,

## Highlights
✔️ Good styling and design for the app
✔️ Passing tests

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-14 09:57 UTC, DammyShittu commented on README.md
> +- Live Demo [Link](https://budget-app-racha.onrender.com/)
- [ ] Kindly ensure your app is well deployed. It shows an error when I click the link.

  ![image](https://github.com/rachaouldbabaali/budget-app/assets/54848363/d5cc64f7-9d2f-4a14-8ab1-07706e0e1ca7)

2023-09-14 15:04 UTC, rachaouldbabaali commented
thank you @DammyShittu the issue is fixed

2023-09-14 15:51 UTC, descholar-ceo approved these changes
Hi @rachaouldbabaali 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Your project passes all test cases ✔️ 
👍🏽 Now The project's live demo link works fine ✔️ 
👍🏽 The styling is commendable ✔️ 
👍🏽 The readme file is professional and it has all headers / sections as described from microverse's readme template ✔️
👍🏽 The video recording explains the project clearly ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-14 15:55 UTC, rachaouldbabaali commented
Thank you , I truly appreciate your time and efforts in reviewing my work

2023-09-14 15:55 UTC, merged